// Package docs is generated by swag. Run `swag init` to regenerate.
// DO NOT EDIT this file manually.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://example.com/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/process-payment": {
            "post": {
                "description": "Simulate secure payment processing. Validates the request and returns a transaction ID on success.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["payments"],
                "summary": "Process a payment",
                "parameters": [
                    {
                        "description": "Payment request payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment processed successfully",
                        "schema": {
                            "$ref": "#/definitions/response.PaymentSuccess"
                        }
                    },
                    "400": {
                        "description": "Validation or business rule failure",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status",
                "produces": ["application/json"],
                "tags": ["system"],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/response.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.PaymentRequest": {
            "description": "Payment request payload",
            "type": "object",
            "required": ["amount", "paymentToken"],
            "properties": {
                "amount": {
                    "description": "Amount to charge; must be greater than 0",
                    "type": "number",
                    "example": 100.50
                },
                "paymentToken": {
                    "description": "Opaque payment token from the client; never stored or logged in full",
                    "type": "string",
                    "example": "tok_test_123"
                }
            }
        },
        "response.PaymentSuccess": {
            "description": "Successful payment response",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "transactionId": {
                    "type": "string",
                    "example": "txn_550e8400-e29b-41d4-a716-446655440000"
                },
                "message": {
                    "type": "string",
                    "example": "Payment processed successfully"
                }
            }
        },
        "response.ErrorResponse": {
            "description": "Error response envelope",
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Invalid payment request"
                },
                "error": {
                    "type": "string",
                    "example": "amount must be greater than 0"
                }
            }
        },
        "response.HealthResponse": {
            "description": "Health check response",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "service": {
                    "type": "string",
                    "example": "payment-service"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Payment Processing API",
	Description:      "A simulated fintech payment processing microservice built with Go and Gin.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
